apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
  creationTimestamp: null
  name: metrics
  namespace: dev
spec:
  rules:
  - host: training-user-6.training.weave.works
  - http:
      paths:
      - backend:
          serviceName: metrics
          servicePort: 3000
        path: /metrics
  tls:
    - hosts:
      - training-6.training.weave.works
    secretName: ingress-certificate
status:
  loadBalancer: {}
