apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  creationTimestamp: null
  name: mighty-fine
  namespace: dev
spec:
  rules:
  - host: training-user-6.training.weave.works
  - http:
      paths:
      - backend:
          serviceName: mighty-fine
          servicePort: 3000
        path: /mighty-fine
  tls:
    - hosts:
      - training-6.training.weave.works
    secretName: ingress-certificate
status:
  loadBalancer: {}
