---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mighty-fine
  namespace: dev
  annotations:
    flux.weave.works/tag.metrics: glob:*
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: metrics-demo
        image: quay.io/brice/metrics-demo:v4-subscription-service
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
